/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author Pedro
 */
public class TelaAdvinhaNumero extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdvinhaNumero
     */
    public TelaAdvinhaNumero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        lblTextoValor = new javax.swing.JLabel();
        spnPalpite = new javax.swing.JSpinner();
        btnPalpite = new javax.swing.JButton();
        lblResposta = new javax.swing.JLabel();
        lblImagemGenio = new javax.swing.JLabel();
        lblImagemBalao = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextoValor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTextoValor.setText("Valor");
        getContentPane().add(lblTextoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        spnPalpite.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        spnPalpite.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 80, -1));

        btnPalpite.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnPalpite.setText("Palpite");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        lblResposta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblResposta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResposta.setText("<html>Vou pensar em um valor entre <strong>1 e 5</strong> tente adivinhar</html>");
        getContentPane().add(lblResposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 140, 80));

        lblImagemGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/genio.png"))); // NOI18N
        getContentPane().add(lblImagemGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 194, -1));

        lblImagemBalao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/balao-de-fala.png"))); // NOI18N
        getContentPane().add(lblImagemBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
    * Compara um número aleatório entre 1 e 5 com o valor inserido pelo 
    * usuário e exibe se o palpite foi correto ou incorreto.
    *
    * @param evt evento de clique do botão
    */
    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        // Gera um número aleatório entre 1 e 5
        int numero = (int)(Math.random() * 5) + 1; 
        
        // Recupera o valor digitado pelo usuário no spinner (convertendo para inteiro)
        int palpite = Integer.parseInt(spnPalpite.getValue().toString());
        
        // Verifica se o palpite é igual ao número sorteado
    // Se for igual, mostra "Acertou!!!", caso contrário mostra "Errou!" e o número sorteado
        String resultado = palpite == numero ? "Acertou!!!" : "Errou!\nEu pensei no número " + numero;
       
        // Exibe o resultado formatado em negrito no JLabel
        lblResposta.setText("<html><strong>" + resultado + "</strong></html>");
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdvinhaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdvinhaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdvinhaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdvinhaNumero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdvinhaNumero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel lblImagemBalao;
    private javax.swing.JLabel lblImagemGenio;
    private javax.swing.JLabel lblResposta;
    private javax.swing.JLabel lblTextoValor;
    private javax.swing.JSpinner spnPalpite;
    // End of variables declaration//GEN-END:variables
}
